type IndiaDistricts = {
  [state: string]: string[];
};

export const indiaStatesAndUTs: string[] = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands', // Union Territory
  'Chandigarh', // Union Territory
  'Dadra and Nagar Haveli and Daman and Diu', // Union Territory
  'Lakshadweep', // Union Territory
  'Delhi', // National Capital Territory (NCT)
  'Puducherry', // Union Territory
];

export const indiaDistricts: IndiaDistricts = {
  'Andhra Pradesh': [
    'Anantapur',
    'Chittoor',
    'East Godavari',
    'Guntur',
    'Kadapa',
    'Krishna',
    'Kurnool',
    'Prakasam',
    'Srikakulam',
    'Visakhapatnam',
    'Vizianagaram',
    'West Godavari',
    'Nellore',
    'Mahbubnagar',
    'Nalgonda',
    'Khammam',
    'Warangal',
    'Medak',
    'Rangareddy',
    'Hyderabad',
  ],
  'Arunachal Pradesh': [
    'Tawang',
    'West Kameng',
    'East Kameng',
    'Papum Pare',
    'Kurung Kumey',
    'Kra Daadi',
    'Upper Subansiri',
    'Lower Subansiri',
    'West Siang',
    'East Siang',
    'Siyomi',
    'Dibang Valley',
    'Anjaw',
    'Lohit',
    'Namsai',
    'Changlang',
    'Tirap',
    'Longding',
  ],
  Assam: [
    'Barpeta',
    'Bongaigaon',
    'Cachar',
    'Darrang',
    'Dibrugarh',
    'Goalpara',
    'Golaghat',
    'Hailakandi',
    'Jorhat',
    'Kamrup',
    'Kamrup Metropolitan',
    'Karbi Anglong',
    'Karimganj',
    'Kokrajhar',
    'Lakhimpur',
    'Majuli',
    'Morigaon',
    'Nagaon',
    'Nalbari',
    'Sivasagar',
    'Sonitpur',
    'Tinsukia',
    'Udalguri',
    'Upper Siang',
    'Charaideo',
    'Dima Hasao',
  ],
  Bihar: [
    'Araria',
    'Arwal',
    'Aurangabad',
    'Banka',
    'Begusarai',
    'Bhagalpur',
    'Bhojpur',
    'Buxar',
    'Darbhanga',
    'East Champaran',
    'Gaya',
    'Gopalganj',
    'Jamui',
    'Jehanabad',
    'Kaimur',
    'Katihar',
    'Khagaria',
    'Kishanganj',
    'Lakhisarai',
    'Madhepura',
    'Madhubani',
    'Munger',
    'Muzaffarpur',
    'Nalanda',
    'Nawada',
    'Patna',
    'Purnia',
    'Rohtas',
    'Saharsa',
    'Samastipur',
    'Saran',
    'Sheikhpura',
    'Sheohar',
    'Sitamarhi',
    'Supaul',
    'Vaishali',
    'West Champaran',
  ],
  Chhattisgarh: [
    'Balod',
    'Baloda Bazar',
    'Balrampur',
    'Bastar',
    'Bemetara',
    'Bijapur',
    'Bilaspur',
    'Dantewada',
    'Dhamtari',
    'Durg',
    'Janjgir-Champa',
    'Jashpur',
    'Kabirdham',
    'Kanker',
    'Kondagaon',
    'Korba',
    'Koriya',
    'Mahasamund',
    'Mungeli',
    'Narayanpur',
    'Raigarh',
    'Raipur',
    'Rajnandgaon',
    'Sarguja',
    'Surajpur',
    'Surguja',
  ],
  Goa: ['North Goa', 'South Goa'],
  Gujarat: [
    'Ahmedabad',
    'Amreli',
    'Anand',
    'Aravalli',
    'Banaskantha',
    'Bharuch',
    'Bhavnagar',
    'Botad',
    'Chhota Udepur',
    'Dahod',
    'Dang',
    'Devbhoomi Dwarka',
    'Gandhinagar',
    'Gir Somnath',
    'Jamnagar',
    'Junagadh',
    'Kachchh',
    'Kheda',
    'Mahisagar',
    'Mehsana',
    'Morbi',
    'Narmada',
    'Navsari',
    'Panchmahal',
    'Patan',
    'Porbandar',
    'Rajkot',
    'Sabarkantha',
    'Surat',
    'Surendranagar',
    'Tapi',
    'Vadodara',
    'Valsad',
  ],
  Haryana: [
    'Ambala',
    'Bhiwani',
    'Charkhi Dadri',
    'Faridabad',
    'Fatehabad',
    'Gurugram',
    'Hisar',
    'Jhajjar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Kurukshetra',
    'Mahendragarh',
    'Mewat',
    'Palwal',
    'Panchkula',
    'Panipat',
    'Rewari',
    'Rohtak',
    'Sirsa',
    'Sonipat',
    'Yamunanagar',
  ],
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Hamirpur',
    'Kangra',
    'Kullu',
    'Kullu Manali',
    'Mandi',
    'Shimla',
    'Sirmaur',
    'Solan',
    'Una',
  ],
  Jharkhand: [
    'Bokaro',
    'Chatra',
    'Deoghar',
    'Dhanbad',
    'Dumka',
    'East Singhbhum',
    'Garhwa',
    'Giridih',
    'Godda',
    'Gumla',
    'Hazaribagh',
    'Jamtara',
    'Khunti',
    'Koderma',
    'Latehar',
    'Lohardaga',
    'Pakur',
    'Palamu',
    'Ramgarh',
    'Ranchi',
    'Sahibganj',
    'Seraikela-Kharsawan',
    'Simdega',
    'West Singhbhum',
  ],
  Karnataka: [
    'Bagalkot',
    'Bangalore Rural',
    'Bangalore Urban',
    'Belagavi',
    'Ballari',
    'Bidar',
    'Chamarajanagar',
    'Chikkaballapur',
    'Chikkamagaluru',
    'Chitradurga',
    'Dakshina Kannada',
    'Davangere',
    'Dharwad',
    'Gadag',
    'Hassan',
    'Haveri',
    'Kalaburagi',
    'Kodagu',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysuru',
    'Raichur',
    'Ramanagara',
    'Shivamogga',
    'Tumakuru',
    'Udupi',
    'Uttara Kannada',
    'Vijayapura',
    'Yadgir',
  ],
  Kerala: [
    'Alappuzha',
    'Ernakulam',
    'Idukki',
    'Kottayam',
    'Kozhikode',
    'Malappuram',
    'Palakkad',
    'Pathanamthitta',
    'Thiruvananthapuram',
    'Thrissur',
    'Wayanad',
  ],
  'Madhya Pradesh': [
    'Alirajpur',
    'Anuppur',
    'Ashok Nagar',
    'Balaghat',
    'Barwani',
    'Betul',
    'Bhind',
    'Bhopal',
    'Burhanpur',
    'Chhindwara',
    'Damoh',
    'Datia',
    'Dewas',
    'Dhar',
    'Dindori',
    'Guna',
    'Gwalior',
    'Harda',
    'Hoshangabad',
    'Indore',
    'Jabalpur',
    'Jhabua',
    'Katni',
    'Khandwa',
    'Khargone',
    'Mandla',
    'Mandsaur',
    'Morena',
    'Narsinghpur',
    'Neemuch',
    'Panna',
    'Raisen',
    'Rajgarh',
    'Ratlam',
    'Rewa',
    'Sagar',
    'Satna',
    'Sehore',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shivpuri',
    'Sidhi',
    'Singrauli',
    'Tikamgarh',
    'Ujjain',
    'Umaria',
    'Vidisha',
  ],
  Maharashtra: [
    'Ahmednagar',
    'Akola',
    'Amravati',
    'Aurangabad',
    'Beed',
    'Bhandara',
    'Buldhana',
    'Chandrapur',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Jalna',
    'Kolhapur',
    'Latur',
    'Mumbai City',
    'Mumbai Suburban',
    'Nagpur',
    'Nanded',
    'Nandurbar',
    'Nashik',
    'Osmanabad',
    'Palghar',
    'Parbhani',
    'Pune',
    'Raigad',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sindhudurg',
    'Solapur',
    'Thane',
    'Wardha',
    'Washim',
    'Yavatmal',
  ],
  Manipur: [
    'Bishnupur',
    'Chandel',
    'Churachandpur',
    'Imphal East',
    'Imphal West',
    'Jiribam',
    'Kangpokpi',
    'Noney',
    'Senapati',
    'Tamenglong',
    'Tengnoupal',
    'Thoubal',
    'Ukhrul',
  ],
  Meghalaya: [
    'East Garo Hills',
    'East Khasi Hills',
    'Jaintia Hills',
    'Ri-Bhoi',
    'South Garo Hills',
    'South West Garo Hills',
    'West Garo Hills',
    'West Khasi Hills',
  ],
  Mizoram: [
    'Aizawl',
    'Champhai',
    'Kolasib',
    'Lawngtlai',
    'Lunglei',
    'Mamit',
    'Saiha',
    'Serchhip',
  ],
  Nagaland: [
    'Dimapur',
    'Kohima',
    'Mokokchung',
    'Mon',
    'Peren',
    'Phek',
    'Tuensang',
    'Wokha',
    'Zunheboto',
  ],
  Odisha: [
    'Angul',
    'Balangir',
    'Balasore',
    'Bargarh',
    'Bhadrak',
    'Bolangir',
    'Cuttack',
    'Deogarh',
    'Dhenkanal',
    'Gajapati',
    'Ganjam',
    'Jagatsinghpur',
    'Jajpur',
    'Jharsuguda',
    'Kalahandi',
    'Kandhamal',
    'Kendrapara',
    'Kendujhar',
    'Khurda',
    'Koraput',
    'Malkangiri',
    'Mayurbhanj',
    'Nabarangpur',
    'Nayagarh',
    'Nuapada',
    'Puri',
    'Rayagada',
    'Sambalpur',
    'Subarnapur',
    'Sundargarh',
  ],
  Punjab: [
    'Amritsar',
    'Ludhiana',
    'Jalandhar',
    'Patiala',
    'Bhatinda',
    'Fatehgarh Sahib',
    'Gurdaspur',
    'Muktsar',
    'Tarn Taran',
    'Mansa',
    'Rupnagar',
    'Faridkot',
    'Sangrur',
    'Barnala',
    'Hoshiarpur',
    'Kapurthala',
    'Moga',
    'Pathankot',
    'Shaheed Bhagat Singh Nagar',
  ],
  Rajasthan: [
    'Jaipur',
    'Udaipur',
    'Jodhpur',
    'Kota',
    'Ajmer',
    'Bhilwara',
    'Bikaner',
    'Churu',
    'Sikar',
    'Tonk',
    'Alwar',
    'Barmer',
    'Nagaur',
    'Pali',
    'Jalore',
    'Rajsamand',
    'Chittorgarh',
    'Dholpur',
    'Banswara',
    'Dungarpur',
    'Sirohi',
    'Jhunjhunu',
    'Sri Ganganagar',
    'Hanumangarh',
    'Bundi',
    'Baran',
    'Jaisalmer',
    'Karauli',
    'Pratapgarh',
    'Dausa',
    'Sawai Madhopur',
  ],
  Sikkim: ['East Sikkim', 'West Sikkim', 'North Sikkim', 'South Sikkim'],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Trichy',
    'Salem',
    'Tirunelveli',
    'Erode',
    'Tiruppur',
    'Vellore',
    'Thanjavur',
    'Kanchipuram',
    'Theni',
    'Cuddalore',
    'Nagapattinam',
    'Karur',
    'Pudukkottai',
    'Dharmapuri',
    'Villupuram',
    'Ramanathapuram',
    'Dindigul',
    'Virudhunagar',
    'Ariyalur',
    'Perambalur',
    'Tiruvallur',
    'Kanyakumari',
    'Nellai',
    'Sivaganga',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Khammam',
    'Nizamabad',
    'Mahabubnagar',
    'Karimnagar',
    'Rangareddy',
    'Adilabad',
    'Medak',
    'Nalgonda',
    'Khammam',
    'Jagtial',
    'Sangareddy',
    'Jagitial',
    'Kothagudem',
    'Peddapalli',
    'Jangaon',
    'Nagarkurnool',
    'Vikarabad',
    'Suryapet',
    'Wanaparthy',
    'Mulugu',
    'Bhadradri Kothagudem',
  ],
  Tripura: [
    'Agartala',
    'Udaipur',
    'Dharmanagar',
    'Ambassa',
    'Kailashahar',
    'Khowai',
    'Sepahijala',
    'North Tripura',
    'South Tripura',
    'West Tripura',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Varanasi',
    'Agra',
    'Noida',
    'Ghaziabad',
    'Aligarh',
    'Moradabad',
    'Bareilly',
    'Meerut',
    'Firozabad',
    'Muzaffarnagar',
    'Mathura',
    'Saharanpur',
    'Jaunpur',
    'Rampur',
    'Basti',
    'Sitapur',
    'Faizabad',
    'Gorakhpur',
    'Barabanki',
    'Shahjahanpur',
    'Ballia',
    'Raebareli',
    'Pratapgarh',
    'Unnao',
    'Deoria',
    'Lalitpur',
    'Mau',
    'Mainpuri',
    'Azamgarh',
    'Bahraich',
    'Sambhal',
    'Sultanpur',
    'Amroha',
    'Badaun',
    'Ambedkar Nagar',
    'Jalaun',
    'Gonda',
    'Kanpur Dehat',
    'Kanpur Nagar',
    'Sant Kabir Nagar',
    'Chandauli',
  ],
  Uttarakhand: [
    'Dehradun',
    'Nainital',
    'Haridwar',
    'Rishikesh',
    'Mussoorie',
    'Almora',
    'Pauri Garhwal',
    'Tehri Garhwal',
    'Udham Singh Nagar',
    'Bageshwar',
    'Pithoragarh',
    'Champawat',
    'Rudraprayag',
    'Chamoli',
    'Nainital',
    'Bijnor',
    'Saharanpur',
  ],
  'West Bengal': [
    'Kolkata',
    'Siliguri',
    'Durgapur',
    'Asansol',
    'Kalyani',
    'Howrah',
    'Hooghly',
    'Midnapore',
    'Purulia',
    'Murshidabad',
    'Birbhum',
    'Bankura',
    'Jalpaiguri',
    'Cooch Behar',
    'Alipurduar',
    'Nadia',
    'South 24 Parganas',
    'North 24 Parganas',
    'Darjeeling',
    'Malda',
    'Bardhaman',
    'Purba Medinipur',
    'Paschim Medinipur',
  ],
  'Andaman and Nicobar Islands': [
    'North and Middle Andaman',
    'South Andaman',
    'Nicobar',
  ],
  Chandigarh: ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Dadra and Nagar Haveli',
    'Daman',
    'Diu',
  ],
  Lakshadweep: ['Lakshadweep'],
  Delhi: [
    'Central Delhi',
    'East Delhi',
    'New Delhi',
    'North Delhi',
    'North East Delhi',
    'North West Delhi',
    'Shahdara',
    'South Delhi',
    'South West Delhi',
    'West Delhi',
  ],
  Puducherry: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
};
